### ISSUE TITLE
Exception #0 (Magento\Framework\Exception\LocalizedException): Area code is not set

### ISSUE THREAD

**Issue by payam427** [magento/magento2-zray#4]
Hi,

When I enable this plugin (on a Magento EE 2.1.2 website), it only works fine on homepage.
On other pages, I get the below exception:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Area code is not set

Exception #0 (Magento\Framework\Exception\LocalizedException): Area code is not set
#0 /usr/local/zend/var/plugins/magento2/zray/zray.php(265): Magento\Framework\App\State->getAreaCode()
#1 /var/www/public/dcw/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento2\Magento->callObserverMethodStart(Array, Array)
#2 /var/www/public/dcw/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Logging\Observer\ModelLoadAfterObserver), Object(Magento\Framework\Event\Observer))
#3 /var/www/public/dcw/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#4 /var/www/public/dcw/var/generation/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('model_load_afte...', Array)
#5 /var/www/public/dcw/vendor/magento/framework/Model/AbstractModel.php(575): Magento\Staging\Model\Event\Manager\Proxy->dispatch('model_load_afte...', Array)
#6 /var/www/public/dcw/vendor/magento/framework/Model/AbstractModel.php(532): Magento\Framework\Model\AbstractModel->_afterLoad()
#7 /var/www/public/dcw/vendor/magento/framework/Flag.php(100): Magento\Framework\Model\AbstractModel->load('staging', 'flag_code')
#8 /var/www/public/dcw/vendor/magento/module-staging/Model/Update/VersionHistory.php(78): Magento\Framework\Flag->loadSelf()
#9 /var/www/public/dcw/vendor/magento/module-staging/Model/Update/VersionHistory.php(58): Magento\Staging\Model\Update\VersionHistory->getFlag()
#10 /var/www/public/dcw/vendor/magento/module-staging/Model/VersionManager.php(161): Magento\Staging\Model\Update\VersionHistory->getCurrentId()
#11 /var/www/public/dcw/vendor/magento/module-staging/Model/VersionManager.php(113): Magento\Staging\Model\VersionManager->getCurrentVersionId()
#12 /var/www/public/dcw/var/generation/Magento/Staging/Model/VersionManager/Interceptor.php(37): Magento\Staging\Model\VersionManager->getVersion()
#13 /var/www/public/dcw/vendor/magento/module-staging/Model/VersionManager.php(152): Magento\Staging\Model\VersionManager\Interceptor->getVersion()
#14 /var/www/public/dcw/var/generation/Magento/Staging/Model/VersionManager/Interceptor.php(76): Magento\Staging\Model\VersionManager->isPreviewVersion()
#15 /var/www/public/dcw/vendor/magento/module-staging/Plugin/Store/Model/StoreResolver.php(57): Magento\Staging\Model\VersionManager\Interceptor->isPreviewVersion()
#16 /var/www/public/dcw/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Staging\Plugin\Store\Model\StoreResolver->aroundGetCurrentStoreId(Object(Magento\Store\Model\StoreResolver\Interceptor), Object(Closure))
#17 /var/www/public/dcw/var/generation/Magento/Store/Model/StoreResolver/Interceptor.php(26): Magento\Store\Model\StoreResolver\Interceptor->___callPlugins('getCurrentStore...', Array, Array)
#18 /var/www/public/dcw/vendor/magento/module-store/Model/StoreManager.php(151): Magento\Store\Model\StoreResolver\Interceptor->getCurrentStoreId()
#19 /var/www/public/dcw/var/generation/Magento/Store/Model/StoreManager/Interceptor.php(76): Magento\Store\Model\StoreManager->getStore(NULL)
#20 /var/www/public/dcw/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager\Interceptor->getStore(NULL)
#21 /var/www/public/dcw/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#22 /var/www/public/dcw/vendor/magento/framework/App/Config/ScopePool.php(147): Magento\Store\Model\Resolver\Store->getScope(NULL)
#23 /var/www/public/dcw/vendor/magento/framework/App/Config/ScopePool.php(93): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#24 /var/www/public/dcw/vendor/magento/framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#25 /var/www/public/dcw/vendor/magento/module-backend/App/Area/FrontNameResolver.php(96): Magento\Framework\App\Config->getValue('admin/url/use_c...', 'store')
#26 /var/www/public/dcw/vendor/magento/module-backend/App/Area/FrontNameResolver.php(79): Magento\Backend\App\Area\FrontNameResolver->isHostBackend()
#27 /var/www/public/dcw/vendor/magento/framework/App/AreaList.php(73): Magento\Backend\App\Area\FrontNameResolver->getFrontName(true)
#28 /var/www/public/dcw/vendor/magento/framework/App/Http.php(130): Magento\Framework\App\AreaList->getCodeByFrontName('about-us')
#29 /var/www/public/dcw/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#30 /var/www/public/dcw/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#31 {main}
```

Thanks,

**Comment by okobchenko** [comment]
Thank you for reporting the issue, but this repository as well as project is no longer maintained.
